apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka2mysql-service
  name: kafka2mysql-service
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
        matchLabels:
            app: kafka2mysql-service
  template:
    metadata:
      labels:
        app: kafka2mysql-service
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: kafka-endpoint
            - configMapRef:
                name: mysql-master-connections
          image: supakornbabe/spai-kafka2mysql-service:dev-15a3550
          imagePullPolicy: Always
          name: kafka2mysql-service
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
